### PR TITLE
Jh

### PR DESCRIPTION
**Pull request by jangjh0421**
1. JavaDoc added for delete note use case
2. Javadoc added for generate quiz use case
3. Generate quiz use case improved -- entity generation is now successful

### CODE REVIEW

**Comment by vivjd** [comment]
I get an error when running your branch and clicking the ViewAllQuizzes button: `readStartArray can only be called when CurrentBSONType is ARRAY, not when CurrentBSONType is DOCUMENT`.

Could you try running it again and see if you get it?

**Comment by jangjh0421** [comment]
oh yes i see the same error

**Review by vivjd — APPROVED** [review]
Thank you @mintun-myo-2020 and @jangjh0421.

The error is not present anymore and it's running successfully.

**Review by vivjd — APPROVED** [review]
Looks good.

**Pull request merged**
